spring:
  config:
    activate:
      on-profile: dev

eureka:
  instance:
    hostname: 127.0.0.1

  client:
    service-url:
      defaultZone: https://k9c201.p.ssafy.io/discovery/eureka
    register-with-eureka: true
    fetch-registry: true
