server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true

      routes:
#        - id: submitService
#          uri: http://localhost:9001/
#          predicates:
#            - Path=/submit/**
#          filters:
#            - AddRequestHeader=submit-request, submit-request-header2
#            - AddResponseHeader=submit-request, submit-request-header2

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**

        - id: submit-service
          uri: lb://SUBMIT-SERVICE
          predicates:
            - Path=/submit/**
          filters:
            - CustomFilter

        - id: api-service
          uri: lb://API-SERVICE
          predicates:
            - Path=/server/**
          filters:
            - CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: HI, I'm LoggerFilter
                preLogger: true
                postLogger: true

