spring:
  config:
    activate:
      on-profile: dev

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: https://k9c201.p.ssafy.io/discovery/eureka
    register-with-eureka: true
    fetch-registry: true
