spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://k9c201.p.ssafy.io:3000"
              - "http://localhost:3000"
              - "https://k9c201.p.ssafy.io"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"
            allow-credentials: true
        add-to-simple-url-handler-mapping: true

      routes:
        - id: first-submit
          uri: lb://FIRST-SUBMIT-SERVICE
          predicates:
            - Path=/movie/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/movie/(?<segment>.*), /${segment}
