spring:
  cloud:
      routes:
        - id: first-submit
          uri: lb://FIRST-SUBMIT-SERVICE
          predicates:
            - Path=/movie/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/movie/(?<segment>.*), /${segment}
            - name: LoggingFilter
              args:
                baseMessage: HI
                preLogger: true
                postLogger: true
