server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://https://lab.ssafy.com/s09-final/S09P31S106/-/tree/BE-config/develop/config