server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://lab.ssafy.com/s09-final/S09P31S106
          username: token
          password: v7HsttLQ6cHWxLb_vkK_
          search-paths: config
          default-label: BE-config/develop
